### PR TITLE
Proper authorship/versioning

### PR DESCRIPTION
**Pull request by LandonTClipp**
Adding proper authorship to files (to be reflected on PyPi).

### CODE REVIEW

**Comment by LandonTClipp** [comment]
FYI I love this package, you did a great job. Previously I've manually implemented master-slave, this is a much better solution. Currently using it to build a massively parallel application on supercomputer :)

**Comment by LandonTClipp** [comment]
Also, add this to your README.rst for the PyPi badge:

```
.. image:: https://badge.fury.io/py/mpi-master-slave.svg
    :target: https://badge.fury.io/py/mpi-master-slave
```
I could make another pull request for this, but probably easier for you to do this.

**Comment by luca-s** [comment]
You should leave your name too in the authors list.

**Comment by luca-s** [comment]
I added the PyPi badge and your name.

**Pull request merged**
